language: python
services:
- docker
cache:
  pip: true
  directories:
  - $HOME/google-cloud-sdk/
python: '2.7'
dist: trusty
sudo: required
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install coveralls
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl
script: coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success: coveralls
deploy:
- provider: script
  script: ./deploy.sh $TRAVIS_BRANCH
  on:
    repo: m-lab/scraper-sync
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-*
- provider: script
  script: ./deploy.sh staging
  on:
    repo: m-lab/scraper-sync
    branch: staging

before_install:
- travis/decrypt.sh "$encrypted_a3d09b9fe230_key" "$encrypted_a3d09b9fe230_iv"
  keys/credentials.tar.gz.enc /tmp/credentials.tar /tmp;
