language: python
services:
- docker
cache:
  pip: true
  directories:
  - $HOME/google-cloud-sdk/
python: '2.7'
dist: trusty
sudo: required
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install coveralls
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- yes | ${HOME}/google-cloud-sdk/bin/gcloud components install kubectl
script: coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success: coveralls
deploy:
- provider: script
  script: ./deploy.sh staging
  on:
    repo: m-lab/scraper-sync
    branch: staging

before_install:
- if [[ -n "$encrypted_a3d09b9fe230_iv" ]]; then
  travis/decrypt.sh "$encrypted_a3d09b9fe230_iv" "$encrypted_a3d09b9fe230_key"
  keys/credentials.tar.gz.enc /tmp/credentials.tar /tmp;
  fi
