language: python
services:
- docker
cache:
  pip: true
  directories:
  - $HOME/google-cloud-sdk/
python: '2.7'
dist: trusty
sudo: required
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install coveralls
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl
script: coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success: coveralls
deploy:
####################################
## Sandbox
- provider: script
  script: ./deploy.sh $TRAVIS_BRANCH travis
  on:
    repo: m-lab/scraper-sync
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-*

####################################
## Staging
- provider: script
  script: ./deploy.sh staging travis
  on:
    repo: m-lab/scraper-sync
    all_branches: true
    condition: $TRAVIS_BRANCH == staging && $TRAVIS_EVENT_TYPE == push

####################################
## Production
- provider: script
  script: ./deploy.sh production travis
  on:
    repo: m-lab/scraper-sync
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

before_install:
- travis/decrypt.sh "$encrypted_c6050636c18f_key" "$encrypted_c6050636c18f_iv"
  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp
