language: python
cache:
  pip: true
  directories:
    - "$HOME/google-cloud-sdk/"
python: "2.7"
dist: trusty
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
  - $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
script:
  coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success:
  coveralls

deploy:
- provider: script
  script:
  - build  # Build Docker image
  - upload # Upload it to gcr.io
  - create the deploy.yml file from template  #
  - deploy # kubectl apply -f ...
