language: python
cache:
  pip: true
  directories:
  - $HOME/google-cloud-sdk/
python: '2.7'
dist: trusty
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install coveralls
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
script: coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success: coveralls
deploy:
- provider: script
  script:
  - cd $TRAVIS_BUILD_DIR && mkdir deployment && cp deploy.yml deployment/
  - cd $TRAVIS_BUILD_DIR && ./travis/build_and_deploy_container.sh ${TRAVIS_COMMIT}
    gcr.io/mlab-staging/github-m-lab-scraper mlab-staging scraper-cluster us-central1-a
    SPREADSHEET_ID 143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY
    NAMESPACE scraper
    GITHUB_COMMIT http://github.com/${TRAVIS_REPO_SLUG}/tree/${TRAVIS_COMMIT}
  on:
    repo: m-lab/scraper-sync
    branch: staging

before_install:
- travis/decrypt.sh "$encrypted_a3d09b9fe230_iv" "$encrypted_a3d09b9fe230_key"
  keys/credentials.tar.gz.enc /tmp/credentials.tar /tmp
