language: python
# Require docker on the Travis nodes because we test the code inside its
# container and we use docker for deployment.
services:
- docker
cache:
  pip: true
  directories:
  - $HOME/google-cloud-sdk/
python: '2.7'
dist: trusty
sudo: required
install:
# Required for code coverage
- pip install coveralls
script: ./pre-commit.sh && ./prepare-commit-msg.sh
after_success: coveralls
