kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: scraper-sync
  labels:
    app: scraper-sync
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        source: '{{GITHUB_COMMIT}}'
      name: scraper-sync
      labels:
        app: scraper-sync
    spec:
      containers:
        - name: scraper-sync
          image: '{{IMAGE_URL}}'
          env:
            - name: NAMESPACE
              value: '{{NAMESPACE}}'
            - name: SPREADSHEET
              value: '{{SPREADSHEET_ID}}'
