kind: Service
apiVersion: v1
metadata:
  name: scraper-sync-public-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector:
    application: scraper-sync
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 9090
    targetPort: 9090
  sessionAffinity: None
  externalIPs:
    - {{EXTERNAL_IP}}
  type: ClusterIP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: scraper-sync
  labels:
    application: scraper-sync
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        source: '{{GITHUB_COMMIT}}'
      name: scraper-sync
      labels:
        application: scraper-sync
    spec:
      # Scraper nodes have sheets permission scopes, and we need sheets
      # permissions to write to the spreadsheet.
      # TODO(https://github.com/m-lab/scraper-sync/issues/40)
      nodeSelector:
        scraper-node: 'true'
      containers:
        - name: scraper-sync
          image: '{{IMAGE_URL}}'
          env:
            - name: NAMESPACE
              value: '{{NAMESPACE}}'
            - name: SPREADSHEET
              value: '{{SPREADSHEET_ID}}'
          ports:
            - containerPort: 80
            - containerPort: 9090
